### ISSUE TITLE
autoload issue with netaddr gem in eos_varp type

### ISSUE THREAD

**Issue by rknaus** [arista-eosplus/puppet-eos#101]
We have an issue with the munge function of the eos_varp type because it uses an external gem (netaddr). When using the type in our puppet module we get the following error when the puppet agent runs:

---

clnchsw19f2bez#bash sudo ip netns exec ns-cloud-mgmt /opt/puppetlabs/bin/puppet agent --environment production --server rh7pt-64.mgmt.sccloudpoc.net --confdir /persist/sys/puppet --daemonize --no-onetime -t --trace
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Warning: Found multiple default providers for package: yum, puppet_gem, pip3; using yum
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/eos_varp: no such file to load -- netaddr at /etc/puppetlabs/code/environments/production/modules/nc_arista_eos/manifests/flavors/leaf.pp:206:3 at /etc/puppetlabs/code/environments/production/modules/role_base/manifests/flavors.pp:25 on node clnchsw19f2bez.mgmt.sccloudpoc.net
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/rest.rb:212:in `is_http_200?'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/rest.rb:110:in`find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:194:in `find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:377:in`block in retrieve_new_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:386:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in`realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:385:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:376:in`retrieve_new_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:78:in `retrieve_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:147:in`prepare_and_retrieve_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:281:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:186:in`block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:240:in`override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:185:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:45:in`block (4 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:45:in`block (3 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:98:in `with_client'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:42:in`block (2 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:65:in `run_in_fork'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:41:in`block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:179:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:179:in`controlled_run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:39:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:353:in`onetime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:331:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in`block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:540:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in`run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:128:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in`execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
'sudo ip netns exec ns-cloud-mgmt /opt/puppetlabs/bin/puppet agent --environment production --server rh7pt-64.mgmt.sccloudpoc.net --confdir /persist/sys/puppet --daemonize --no-onetime -t --trace' returned error code:1
clnchsw19f2bez#

---

In our puppet module we use the resource like this:
  # create the varp mac address
  eos_varp { 'settings':
      mac_address => $default_varp_mac_address,
  }

Would it be possible to remove the munge function with the used netaddr gem (https://github.com/arista-eosplus/puppet-eos/blob/develop/lib/puppet/type/eos_varp.rb#L53) and validate the mac address with a simple regex?

Or is there a way to avoid the autoload issue with puppet?

**Comment by jerearista** [comment]
I'm curious how you installed rbeapi without netaddr.  What version of the puppet-agent are you using and what type of package did you use to install rbeapi? The SWIX file provided in rbeapi releases includes netaddr, inifile, and net_http_unix gems all of which should have been required to install rbeapi.

There are 2 ways to get this and the other gems required by rbeapi on the switch in Puppet's supplied Ruby.  Use the rbeapi SWIX file ([rbeapi-puppet-aio-1.0-1.swix](https://github.com/arista-eosplus/rbeapi/releases/download/v1.0/rbeapi-puppet-aio-1.0-1.swix)) installation method for the Puppet all-in-one (AIO) install on EOS or using the [puppet_gem](https://docs.puppet.com/puppet/4.0/reference/type.html#package-provider-puppet_gem) provider for the package resource.

```
package { 'netaddr' :
  ensure   => installed,
  provider => 'puppet_gem',
}
```

**Comment by rknaus** [comment]
We use the following rbeapi and puppet-agent:
```
clnchsw19f2bez#show extensions 
Name                                       Version/Release           Status extension
------------------------------------------ ------------------------- ------ ----
!<snip>
puppet-agent-1.5.3-1.eos4.i386.swix        1.5.3/1.eos4              A, I      1
rbeapi-puppet-aio-1.0-1.swix               1.0/1.eos4                A, I      4
!<snip>
A: available | NA: not available | I: installed | NI: not installed | F: forced
clnchsw19f2bez#sh ver
Arista DCS-7150S-64-CL-R
Hardware version:    01.02
Serial number:       JPE14050681
System MAC address:  001c.7342.b351

Software image version: 4.15.6M
Architecture:           i386
Internal build version: 4.15.6M-3137476.4156M
Internal build ID:      4a5d9de4-495c-492d-9664-e4122a95d6d5

Uptime:                 1 week, 2 days, 21 hours and 49 minutes
Total memory:           3978148 kB
Free memory:            329516 kB

clnchsw19f2bez#
```

The problem occurs when the catalogue gets evaluated on the puppetserver. I think on the switch everything is ok, but puppet has some trouble loading external gems dynamically.
```
[root@rh7pt-64 ~]# gem list --local | grep netaddr
netaddr (1.5.1)
[root@rh7pt-64 ~]# puppetserver --version
puppetserver version: 2.4.0
[root@rh7pt-64 ~]# puppet --version
4.7.0
[root@rh7pt-64 ~]# 
```

Currently my colleague @mrvinti is working on a workaround in puppet-eos. He will make a pull request soon.

**Comment by jerearista** [comment]
On newer versions, you would want to look at the embedded ruby gems: /opt/puppetlabs/puppet/bin/gem list --local

**Comment by jerearista** [comment]
Ah, the type is evaluating on the puppetserver .   We put in the `feature` and `confine` code in the provider to prevent this type of situation: https://github.com/arista-eosplus/puppet-eos/blob/develop/lib/puppet/provider/eos_varp/default.rb#L41-L42   It is disappointing that Puppet does not evaluate the runtime_dependency list in the gemspec when installing a module.   

I'll discuss the solution in #102 with the team.
