### ISSUE TITLE
Cleanup documentation

### ISSUE THREAD

**Issue by devrobo** [arista-eosplus/puppet-eos#19]
Need to go through and review the generated documentation. Seeing minor issues in the type docstrings.

**Comment by devrobo** [comment]
Need to do a side by side comparison with ansible docstrings.

**Comment by devrobo** [comment]
Need to add a manifest example to each type. Example in eos_staticroute.

**Comment by jerearista** [comment]
Validate the output works with the following commands:

    puppet describe --list | grep eos
    puppet describe [-s] <type>   (Where -s is the summary view)
    puppet doc -r type            (This is the basis for the docs on ReadTheDocs and Forge)
