### ISSUE TITLE
warning: already initialized constant IPADDR_REGEXP in mlag and ipinterface types

### ISSUE THREAD

**Issue by jerearista** [arista-eosplus/puppet-eos#2]
#bash sudo puppet resource --types | grep eos
/var/opt/lib/pe-puppet/lib/puppet/type/eos_mlag.rb:96: warning: already initialized constant IPADDR_REGEXP
/var/opt/lib/pe-puppet/lib/puppet/type/eos_ipinterface.rb:88: warning: already initialized constant IPADDR_REGEXP

**Comment by devrobo** [comment]
Addressed this issue in the release-1.0.0 code cleanup. This commit created the helper file that contains the constant definition: https://github.com/arista-eosplus/puppet-eos/commit/09d98946f98d92b0e7cfcfc9f9a4da0ef0a0cd15
