### ISSUE TITLE
eos_interface not controlling shutdown/enable status properly

### ISSUE THREAD

**Issue by kpmueller** [arista-eosplus/puppet-eos#26]
[root@arista1 ~]# puppet resource eos_interface Loopback1
eos_interface { 'Loopback1':
 ensure => 'present',
 enable => 'false',
}

[root@arista1 ~]# puppet resource eos_interface Loopback1 enable=true
Notice: /Eos_interface[Loopback1]/enable: enable changed 'false' to 'true'
eos_interface { 'Loopback1':
 ensure => 'present',
 enable => 'true',
}

[root@arista1 ~]# puppet resource eos_interface Loopback1
eos_interface { 'Loopback1':
 ensure => 'present',
 enable => 'false',
}

The lack of changes are also reflected in the running-config in the CLI as well

**Comment by devrobo** [comment]
Are you running the latest development version? If so, I pushed a change last week to rbeapi for the upcoming 0.3.0 release that could impact puppet providers. On my todo list before shipping the next puppet-eos release is to make sure all the puppet providers are working properly with the new semantics. Moving forward puppet-eos 1.2.0 and later releases will only work properly with rbeapi 0.3.0 and later.

**Comment by devrobo** [comment]
There were two problems. In puppet-eos, the set_shutdown was passing in symbols instead of boolean values. This is fixed with commit: d7be89b4546df51a7418809279b9aa0f537210c6

In rbeapi, the set_shutdown methods needed to negate the boolean value being passed down.
