### ISSUE TITLE
eos_bgp_neighbor not configuring

### ISSUE THREAD

**Issue by kpmueller** [arista-eosplus/puppet-eos#27]
This is with the rbeapi bgp and puppet-eos bgp feature branches (the one which is waiting in a pull request). I can't figure out how to create an issue in that particular branch, but it seems to be all Arista employees.

The puppet type/provider is not actually changing the configuration successfully:

[root@arista1 /persist/local]# puppet resource eos_bgp_config 65002 enable=true router_id=99.99.99.100
Notice: /Eos_bgp_config[65002]/ensure: created
eos_bgp_config { '65002':
  ensure => 'present',
}
[root@arista1 /persist/local]# puppet resource eos_bgp_config
eos_bgp_config { '65002':
  ensure => 'present',
  enable => 'false',
}

(The puppet resource output at the end also matches the actual CLI configuration)

**Comment by devrobo** [comment]
Hi Karl,
This code is still under development and I have not pushed up all the changes. The BGP types will be supported and working in the upcoming 1.2.0 release. Opening issues against pull requests is not productive.
