### ISSUE TITLE
eos_portchannel members not idempotent when interface order is not the same

### ISSUE THREAD

**Issue by jerearista** [arista-eosplus/puppet-eos#46]
hiera: `eos_config::portchannel::members: ['Ethernet1', 'Ethernet2']`
Switch state: 

```
show port-channel 1 all-ports
Port Channel Port-Channel1:
  Active Ports: Ethernet2 
  Configured, but inactive ports:
       Port         Reason unconfigured                                   
    --------------- ----------------------------------------------------- 
       Ethernet1    LACP negotiated incompatible aggregate (check config) 
```

Produces:

```
Notice: /Stage[main]/Eos_config::Portchannel/Eos_portchannel[Port-Channel1]/members: members changed ['Ethernet2', 'Ethernet1'] to 'Ethernet1 Ethernet2'
```

Suspect this could be equally reproducible in a normal state with `eos_config::portchannel::members: ['Ethernet2', 'Ethernet1']`

**Comment by devrobo** [comment]
Create a puppet test  with interfaces in reverse order and verify that we hit the idempotency issue.
Can we just sort the interface names so they are always processed in the same order?

**Comment by devrobo** [comment]
Turns out fixing this in puppet is very simple. Override the insync? method in the type for the property:

    # Sort the arrays before comparing

    def insync?(current)

      current.sort == should.sort

    end

We need to fix all the types that have this issue.
