### ISSUE TITLE
It is not possible to change a user password if they are encryptet in md5 or sha512

### ISSUE THREAD

**Issue by mmailand** [arista-eosplus/puppet-eos#86]
It is not possible to change a user password if they are encrypted in md5 or sha512

In the rbeapi in the file lib/rbeapi/api/users.rb

line 220 "enc = opts.fetch(:encryption, 'cleartext')"
we default to cleartext if no encryption is set.

In the module puppet-eos file lib/puppet/provider/eos_user/default.rb
line 125 we use the @property_flush to send the changes to rbeapi.

In the case we just want to change the password of a user,  which is encryptet with md5 or sha512,
The @property_flush just contains the :secret not the :encryption therefore in the rbeapi we fallback to cleartext. That is the reason why it is not working.

We should set the :encryption in the @porperty_flush as well to fix that.
Please see my PR.

**Comment by jerearista** [comment]
Closed by arista-eosplus/puppet-eos#87
