### ISSUE TITLE
Gems not Ruby 1.9.3 compatible

### ISSUE THREAD

**Issue by rknaus** [arista-eosplus/puppet-eos#95]
According to the README the types and providers are compatible with Ruby 1.9.3.
When doing a bundle install I get error messages that at least Ruby 2.2.5 is required because of the ruby_dep and json Gem.
@jerearista Is it possible to use older versions of the referenced Gems which are Ruby 1.9.3 compatible?

Error messages with Ruby 1.9.3
`Gem::InstallError: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.`
`Gem::InstallError: json requires Ruby version ~> 2.0.`

**Comment by jerearista** [comment]
We are not using any capabilities which require the new versions and have already started running into this with other gems here and in rbeapi.   I'll add rbuy-dep and json restrictions in the Gemfile as in https://github.com/arista-eosplus/rbeapi/commit/1ce989448fffd6ff2c4603f6b594c541ed71ea5f.  That way we limit the version picked up in Ruby 1.9 but allow newer updates to be used with Ruby 2 and up.

**Comment by rknaus** [comment]
Thanks a lot 👍 !
